#pragma once
#include <noxx/int.hpp>

#include "address-map.hpp"

namespace hw::nvic {
enum class IRQ : u32 {
    WindowWatchdog          = 0,
    PvdPvm                  = 1,
    Rtc                     = 2,
    RtcSecure               = 3,
    Tamper                  = 4,
    RamConfig               = 5,
    Flash                   = 6,
    FlashSecure             = 7,
    Gtzc                    = 8,
    Rcc                     = 9,
    RccSecure               = 10,
    Exti0                   = 11,
    Exti1                   = 12,
    Exti2                   = 13,
    Exti3                   = 14,
    Exti4                   = 15,
    Exti5                   = 16,
    Exti6                   = 17,
    Exti7                   = 18,
    Exti8                   = 19,
    Exti9                   = 20,
    Exti10                  = 21,
    Exti11                  = 22,
    Exti12                  = 23,
    Exti13                  = 24,
    Exti14                  = 25,
    Exti15                  = 26,
    IndependentWatchdog     = 27,
    SecureAes               = 28,
    Gpdma1Channel0          = 29,
    Gpdma1Channel1          = 30,
    Gpdma1Channel2          = 31,
    Gpdma1Channel3          = 32,
    Gpdma1Channel4          = 33,
    Gpdma1Channel5          = 34,
    Gpdma1Channel6          = 35,
    Gpdma1Channel7          = 36,
    Adc1                    = 37,
    Dac1                    = 38,
    Fdcan1It0               = 39,
    Fdcan1It1               = 40,
    Timer1Break             = 41,
    Timer1Update            = 42,
    Timer1TriggerCommutation = 43,
    Timer1Capture           = 44,
    Timer2                  = 45,
    Timer3                  = 46,
    Timer4                  = 47,
    Timer5                  = 48,
    Timer6                  = 49,
    Timer7                  = 50,
    Timer8Break             = 51,
    Timer8Update            = 52,
    Timer8TriggerCommutation = 53,
    Timer8Capture           = 54,
    I2c1Event               = 55,
    I2c1Error               = 56,
    I2c2Event               = 57,
    I2c2Error               = 58,
    Spi1                    = 59,
    Spi2                    = 60,
    Usart1                  = 61,
    Usart2                  = 62,
    Usart3                  = 63,
    Uart4                   = 64,
    Uart5                   = 65,
    LpUart1                 = 66,
    LpTimer1                = 67,
    LpTimer2                = 68,
    Timer15                 = 69,
    Timer16                 = 70,
    Timer17                 = 71,
    Comparator              = 72,
    UsbOtgFs                = 73,
    ClockRecoverySystem     = 74,
    Fmc                     = 75,
    OctoSpi1                = 76,
    PowerStop3Wakeup        = 77,
    Sdmmc1                  = 78,
    Sdmmc2                  = 79,
    Gpdma1Channel8          = 80,
    Gpdma1Channel9          = 81,
    Gpdma1Channel10         = 82,
    Gpdma1Channel11         = 83,
    Gpdma1Channel12         = 84,
    Gpdma1Channel13         = 85,
    Gpdma1Channel14         = 86,
    Gpdma1Channel15         = 87,
    I2c3Event               = 88,
    I2c3Error               = 89,
    Sai1                    = 90,
    Sai2                    = 91,
    TouchSensing            = 92,
    Aes                     = 93,
    Rng                     = 94,
    Fpu                     = 95,
    Hash                    = 96,
    Pka                     = 97,
    LpTimer3                = 98,
    Spi3                    = 99,
    I2c4Error               = 100,
    I2c4Event               = 101,
    Mdf1Filter0             = 102,
    Mdf1Filter1             = 103,
    Mdf1Filter2             = 104,
    Mdf1Filter3             = 105,
    Ucpd1                   = 106,
    InstructionCache        = 107,
    Otfdec1                 = 108,
    Otfdec2                 = 109,
    LpTimer4                = 110,
    DataCache1              = 111,
    Adf1                    = 112,
    Adc4                    = 113,
    Lpdma1Channel0          = 114,
    Lpdma1Channel1          = 115,
    Lpdma1Channel2          = 116,
    Lpdma1Channel3          = 117,
    Dma2d                   = 118,
    DcmiPssi                = 119,
    OctoSpi2                = 120,
    Mdf1Filter4             = 121,
    Mdf1Filter5             = 122,
    Cordic                  = 123,
    Fmac                    = 124,
    LseClockSecuritySystem  = 125,
};

struct Regs {
    v32 set_enable[16];   // ISER0..15, 0x000
    v32 _reserved0[16];   // 0x040
    v32 clear_enable[16]; // ICER0..15, 0x080
};
static_assert(sizeof(Regs) == 0x080 + 16 * 4);
} // namespace hw::nvic

#define NVIC_REGS (*(hw::nvic::Regs*)NVIC_BASE)
