#pragma once
#include <noxx/int.hpp>

namespace halow {
struct FwSegment {
    u32 addr;     // chip memory address
    u32 offset;   // byte offset into the blob (compressed stream)
    u32 comp_len; // compressed length
    u32 orig_len; // uncompressed length (multiple of 4)
};

// self-describing image generated by tools/generate-halow-fw.py, flashed at a
// fixed rom address alongside the bootloader and read in place by the firmware
struct FwStore {
    static constexpr auto magic_value = u32(0x53574648); // "HFWS"

    u32  magic;
    u32  fw_segments_count;
    u32  bcf_segments_count;
    u32  blob_offset; // byte offset from the store base to the blob
    char country[4];  // regdom loaded with the bcf, nul-padded

    // fw segments followed by bcf segments
    auto segments() const -> const FwSegment* {
        return (const FwSegment*)(this + 1);
    }
    auto fw_segments() const -> const FwSegment* {
        return segments();
    }
    auto bcf_segments() const -> const FwSegment* {
        return segments() + fw_segments_count;
    }
    auto blob() const -> const u8* {
        return (const u8*)this + blob_offset;
    }
};
} // namespace halow
