#!/usr/bin/env python3
# extract the s1g regulatory channel tables from morselib's mmregdb.c
# into a C++ table (see struct mmwlan_s1g_channel for the source layout)
import re
import sys


def main():
    src_c, out_hpp, out_cpp = sys.argv[1:4]
    text = open(src_c).read()

    # channel arrays: name -> [(freq_hz, s1g_chan_num, bw_mhz, eirp_dbm)]
    channel_arrays = {}
    for m in re.finditer(
        r"const struct mmwlan_s1g_channel (s1g_channels_\w+)\[\] = \{(.*?)\};",
        text,
        re.S,
    ):
        name, body = m.groups()
        rows = []
        for row in re.finditer(r"\{\s*([-\d]+(?:\s*,\s*[-\w]+)*)\s*\}", body):
            fields = [f.strip() for f in row.group(1).split(",")]
            freq_hz, _duty, _omit, _gop, _s1gop, num, bw, eirp = fields[:8]
            rows.append((int(freq_hz), int(num), int(bw), int(eirp)))
        channel_arrays[name] = rows

    # channel list structs bind a country code to an array or a slice of one;
    # first wins on duplicates (the AU lists share one code, mmregdb selects
    # by build config)
    regdoms = {}
    for m in re.finditer(
        r'\.country_code = "(\w\w)",\s*'
        r"\.num_channels = ([^,]+),\s*"
        r"\.channels = ([^,\s]+),",
        text,
    ):
        country, num, chans = m.groups()
        if country in regdoms:
            continue
        if s := re.fullmatch(r"&(s1g_channels_\w+)\[(\d+)\]", chans):
            start = int(s.group(2))
            regdoms[country] = channel_arrays[s.group(1)][
                start : start + int(num)
            ]
        else:
            regdoms[country] = channel_arrays[chans]

    if not regdoms:
        sys.exit("no channel lists found")

    with open(out_hpp, "w") as f:
        f.write("""// generated by tools/generate-halow-regdb.py -- do not edit
#pragma once
#include <noxx/int.hpp>

namespace halow {
struct S1gChannel {
    u32 freq_khz;
    u8  chan_num; // s1g channel number
    u8  bw_mhz;   // operating bandwidth
    i8  max_tx_eirp_dbm;
};

struct Regdom {
    char              country[3]; // iso 3166-1 alpha-2, nul terminated
    const S1gChannel* channels;
    u32               num_channels;
};

extern const Regdom regdoms[];
extern const u32    regdoms_count;
} // namespace halow
""")

    with open(out_cpp, "w") as f:
        f.write(f"""// generated by tools/generate-halow-regdb.py -- do not edit
// source: {src_c}
#include "halow-regdb.hpp"

namespace halow {{
namespace {{
""")
        for country, rows in regdoms.items():
            f.write(f"constexpr S1gChannel channels_{country}[] = {{\n")
            for freq_hz, num, bw, eirp in rows:
                f.write(f"    {{{freq_hz // 1000}, {num}, {bw}, {eirp}}},\n")
            f.write("};\n")
        f.write("""} // namespace

const Regdom regdoms[] = {
""")
        for country, rows in regdoms.items():
            f.write(
                f'    {{"{country}", channels_{country}, {len(rows)}}},\n'
            )
        f.write(f"""}};
const u32 regdoms_count = {len(regdoms)};
}} // namespace halow
""")

    print(
        f"regdb: {len(regdoms)} regdoms "
        f"({', '.join(regdoms)}), "
        f"{sum(len(r) for r in regdoms.values())} channels"
    )


if __name__ == "__main__":
    main()
