#!/usr/bin/env python3
# Extract the chip-loadable segments from the Morse Micro firmware and BCF ELF
# images (ref/morse-firmware/*) into a flat blob plus a segment table that the
# EKH05 firmware downloader (halow::load_firmware) writes to chip memory.
#
# The blob is stored raw-DEFLATE compressed to keep the host flash image small;
# load_firmware inflates it into RAM (halow::inflate) before writing segments.
# The segment offsets index into the *uncompressed* blob.
#
# The firmware ELF's PT_LOAD program headers map 1:1 onto the mbin FW_SEGMENT
# records the morselib loader would produce (p_paddr -> chip address). The BCF
# ELF keeps the board config and every regulatory domain in named sections; all
# regdoms share one load address, so we pick exactly one country.

import struct
import sys
import zlib


def read_elf_load_segments(path):
    with open(path, "rb") as f:
        data = f.read()
    assert data[:4] == b"\x7fELF", f"{path}: not an ELF file"
    assert data[4] == 1, "expected 32-bit ELF"
    assert data[5] == 1, "expected little-endian ELF"
    (e_phoff,) = struct.unpack_from("<I", data, 0x1C)
    e_phentsize, e_phnum = struct.unpack_from("<HH", data, 0x2A)
    segments = []
    for i in range(e_phnum):
        off = e_phoff + i * e_phentsize
        p_type, p_offset, p_vaddr, p_paddr, p_filesz = struct.unpack_from(
            "<IIIII", data, off
        )
        if p_type != 1 or p_filesz == 0:  # PT_LOAD with data only
            continue
        segments.append((p_paddr, data[p_offset : p_offset + p_filesz]))
    return segments


def read_elf_section(path, name):
    with open(path, "rb") as f:
        data = f.read()
    assert data[:4] == b"\x7fELF", f"{path}: not an ELF file"
    (e_shoff,) = struct.unpack_from("<I", data, 0x20)
    e_shentsize, e_shnum, e_shstrndx = struct.unpack_from("<HHH", data, 0x2E)
    strtab_off = struct.unpack_from(
        "<I", data, e_shoff + e_shstrndx * e_shentsize + 0x10
    )[0]

    def section_name(name_idx):
        end = data.index(b"\x00", strtab_off + name_idx)
        return data[strtab_off + name_idx : end].decode()

    for i in range(e_shnum):
        off = e_shoff + i * e_shentsize
        sh_name, sh_type, sh_flags, sh_addr, sh_offset, sh_size = struct.unpack_from(
            "<IIIIII", data, off
        )
        if section_name(sh_name) == name:
            return sh_addr, data[sh_offset : sh_offset + sh_size]
    raise KeyError(f"{path}: section {name} not found")


def pad4(b):
    if len(b) % 4:
        b = b + b"\x00" * (4 - len(b) % 4)
    return b


def main():
    fw_elf, bcf_elf, country, out_bin, out_hpp, out_cpp = sys.argv[1:7]

    blob = bytearray()
    fw_table = []
    bcf_table = []
    orig_total = 0

    def append(addr, payload):
        nonlocal orig_total
        payload = pad4(payload)
        deflate = zlib.compressobj(9, zlib.DEFLATED, -15)
        compressed = deflate.compress(payload) + deflate.flush()
        offset = len(blob)
        blob.extend(compressed)
        orig_total += len(payload)
        return (addr, offset, len(compressed), len(payload))

    for addr, payload in read_elf_load_segments(fw_elf):
        fw_table.append(append(addr, payload))

    for name in (".board_config", f".regdom_{country}"):
        addr, payload = read_elf_section(bcf_elf, name)
        bcf_table.append(append(addr, payload))

    with open(out_bin, "wb") as f:
        f.write(blob)

    def emit_table(rows):
        return ",\n".join(
            f"    {{0x{a:08x}, 0x{o:x}, 0x{c:x}, 0x{n:x}}}" for a, o, c, n in rows
        )

    with open(out_hpp, "w") as f:
        f.write("""// generated by tools/generate-halow-fw.py -- do not edit
#pragma once
#include <noxx/int.hpp>

namespace halow {
struct FwSegment {
    u32 addr;     // chip memory address
    u32 offset;   // byte offset into fw_blob (compressed stream)
    u32 comp_len; // compressed length
    u32 orig_len; // uncompressed length (multiple of 4)
};
extern const FwSegment fw_segments[];
extern const u32 fw_segments_count;
extern const FwSegment bcf_segments[];
extern const u32 bcf_segments_count;
extern "C" const u8 halow_fw_blob[];
} // namespace halow
""")

    with open(out_cpp, "w") as f:
        f.write(f"""// generated by tools/generate-halow-fw.py -- do not edit
// firmware: {fw_elf}
// bcf: {bcf_elf} (regdom {country})
#include "halow-fw.hpp"

namespace halow {{
const FwSegment fw_segments[] = {{
{emit_table(fw_table)}}};
const u32 fw_segments_count = {len(fw_table)};
const FwSegment bcf_segments[] = {{
{emit_table(bcf_table)}}};
const u32 bcf_segments_count = {len(bcf_table)};
}} // namespace halow

asm(".section .rodata\\n"
    ".balign 4\\n"
    ".global halow_fw_blob\\n"
    "halow_fw_blob:\\n"
    ".incbin \\"{out_bin}\\"\\n");
""")

    largest = max(n for _, _, _, n in fw_table + bcf_table)
    print(
        f"fw: {len(fw_table)} segments; bcf: {len(bcf_table)} segments; "
        f"{orig_total} bytes -> {len(blob)} compressed "
        f"({100 * len(blob) // orig_total}%); "
        f"largest segment {largest} bytes (peak decompress RAM)"
    )


if __name__ == "__main__":
    main()
